### ISSUE TITLE
First empty line at webpage

### ISSUE THREAD

**Issue by sousasag** [DanielAndreasen/SWEET-Cat#1]
I saw this before, but I don't remember how it was fixed.
In the online page it appear an empty line on top. How do we get ride of it?

![image](https://user-images.githubusercontent.com/6715128/58034994-b907a780-7b1f-11e9-8544-99a8cc1cf719.png)

**Comment by acsferreira** [comment]
Daniel has a script that remove the \n in the end of the file. It is done in VIM. We don't  know why but we  can't remove in a different way.

**Comment by sousasag** [comment]
I think the \n is always included in normal editors.... I will try to find out a solution later. For now, is this VIM script in the repository?

**Comment by DanielAndreasen** [comment]
It's part of my .vimrc. I made that on Andressa's laptop as well. But yes, just remove the last \n and it should work again

**Comment by sousasag** [comment]
Python for the rescue:
I added a simple python script to do the job to any file. Of course the better solution would be to change the reading function at the website source code :)
